---
- include_tasks: win_get_install_params.yaml
  when:
    - ansible_os_family == "Windows"
- include_tasks: win_startservice.yaml
  when:
    - ansible_os_family == "Windows"
- include_tasks: win_configuredatastore.yaml
  when:
    - ansible_os_family == "Windows"
- include_tasks: win_post_configuredatastore.yaml
  when:
    - ansible_os_family == "Windows"
# - include_tasks: win_edit_datastoreconnection.yaml
#   when:
#     - ansible_os_family == "Windows"
- include_tasks: win_import_certificates.yaml
  when:
    - ansible_os_family == "Windows"