---
- include_tasks: win_get_install_params.yaml
  when:
    - ansible_os_family == "Windows"
- include_tasks: win_change_serviceaccount.yaml 
  when:
    - ansible_os_family == "Windows"
- include_tasks: win_startservice.yaml
  when:
    - ansible_os_family == "Windows"
- include_tasks: win_configuredatastore.yaml
  when:
    - ansible_os_family == "Windows"
- include_tasks: win_post_configuredatastore.yaml
  when:
    - ansible_os_family == "Windows"
# - include_tasks: win_edit_datastoreconnection.yaml
#   when:
#     - ansible_os_family == "Windows"
- include_tasks: win_import_certificates.yaml
  when:
    - ansible_os_family == "Windows"
### Linux
- include_tasks: get_install_params.yaml
  when:
    - ansible_distribution in ['RedHat','CentOS', 'Debian', 'Ubuntu']
- include_tasks: startservice.yaml
  when:
    - ansible_distribution in ['RedHat','CentOS', 'Debian', 'Ubuntu']
- include_tasks: configuredatastore.yaml
  when:
    - ansible_distribution in ['RedHat','CentOS', 'Debian', 'Ubuntu']
- include_tasks: post_configuredatastore.yaml
  when:
    - ansible_distribution in ['RedHat','CentOS', 'Debian', 'Ubuntu']
- include_tasks: import_certificates.yaml
  when:
    - ansible_distribution in ['RedHat','CentOS', 'Debian', 'Ubuntu']