---
- name: check if site available
  ansible.windows.win_uri:
    url: "{{ datastore_webserver_endpoint }}"
    method: GET
    validate_certs: no
    status_code: 200
  register: datastore_available
  until: datastore_available.status_code == 200
  retries: 60
  delay: 5
