---
- name: set web contexturl with async stop service
  ansible.windows.win_uri:
    url: "{{ system_properties_update_endpoint }}"
    method: POST
    body: "properties={\"WebContextURL\": \"{{ webcontext_url }}\"}&f=json&token={{ tokenresult.json.token }}"
    # body: "properties={\"WebContextURL\": \"{{ webcontext_url }}\",\"portalLocalHostname\": \"{{ portal_internal_fqdn }}\",\"privatePortalURL\":\"https://{{ portal_internal_fqdn }}:7443/arcgis\"}&f=json&token={{ tokenresult.json.token }}"
    validate_certs: no
    content_type: application/x-www-form-urlencoded
    return_content: yes
    headers:
      Referer: "{{ portal_admin_root_endpoint }}"
      # Referer: "https://{{ ansible_facts['nodename'] }}:7443"
  register: edit_webcontexturl
  poll: 0
  async: 60

- name: pause time because upgrade webcontexturl property background process is too long.
  pause:
    seconds: 180

- name: health check arcgis portal
  ansible.windows.win_uri:
    url: "{{ healthcheck_endpoint }}"
    method: GET
    validate_certs: no
    status_code: 200
  register: portal_healthstatus_result
  until: portal_healthstatus_result.status_code == 200
  retries: 180 # 180 = 30 min
  delay: 10 # Every 10 seconds

- debug:
    var: portal_healthstatus_result
