---
- name: create the temporal and extract directory for installers
  win_file:
    path: "{{ win_backup_dir }}"
    state: directory

- name: Add configure to share with arcgis service account
  win_share:
    name: backup
    description: backup share
    path: "{{ win_backup_dir }}"
    full: "{{ arcgis_service_account }}"

- name: copy the webgisdr property file
  win_copy:
    src: "{{ webgisdr_properties_file }}"
    dest: "{{ win_remote_temp_dest_dir }}\\webgisdr.properties"
    force: no