---
- name: health check arcgis service
  ansible.windows.win_uri:
    url: "{{ healthcheck_endpoint }}"
    method: GET
    validate_certs: no
    status_code: 500
  register: portal_available
  until: portal_available.status_code == 500
  retries: 60 # 720 * 5 seconds = 1hour (60*60/5)
  delay: 5 # Every 5 seconds

- debug:
    var: portal_available

- name: create portal site
  win_shell: "{{ win_createportal_shell }}"
  register: createportalresult
  args:
    chdir: "{{ win_createportal_shell_location }}"
    executable: cmd.exe

- name: check portal result
  debug:
    msg: "{{ createportalresult.stdout }}"