---
- name: check if site available after post install
  ansible.windows.win_uri:
    url: "{{ healthcheck_endpoint }}"
    method: GET
    validate_certs: no
    status_code: 200
  register: portal_available
  until: portal_available.status_code == 200
  retries: 60
  delay: 5