---
- name: health check arcgis portal
  ansible.windows.win_uri:
    url: "{{ healthcheck_endpoint }}"
    method: GET
    validate_certs: no
    status_code: 200
  register: portal_healthstatus_result
  until: portal_healthstatus_result.status_code == 200
  retries: 180 # 180 = 30 min
  delay: 10 # Every 10 seconds

- debug:
    var: portal_healthstatus_result
    
- name: generate token
  ansible.windows.win_uri:
    url: "{{ generatetoken_endpoint }}"
    method: POST
    body: "password={{ portal_admin_user_pw }}&username={{ portal_admin_user }}&client=referer&ip=&referer={{ portal_admin_root_endpoint }}&expiration=30&f=json"
    validate_certs: no
    content_type: application/x-www-form-urlencoded
    return_content: yes
    status_code: 200
  register: tokenresult

- debug:
    var: tokenresult
    
- debug:
    var: tokenresult.json.token