---
version: 0.2

phases:
  pre_build:
    commands:
      - git clone https://github.com/tfutils/tfenv.git ~/.tfenv
      - ln -s ~/.tfenv/bin/* /usr/local/bin
  build:
    commands:
      - echo "Set for AWS"
      - cd ./envs/dev/
      - make for-codebuild
      #########################
      - echo "destroy infra"
      - cd ./infra/
      - aws ssm get-parameter --name "/egihssystem/terraform/infravars" | jq -r .Parameter.Value > ./terraform.tfvars
      - tfenv install
      - tfenv use
      - terraform --version
      - terraform init -input=false -no-color
      - terraform plan -input=false -no-color
      - terraform apply -input=false -no-color -auto-approve
      - echo "Good bye the existing infra deployment"
  post_build:
    commands:
      - echo "Now Finished Destroy"