---
- name: check if server is available
  uri:
    url: "{{ portal_healthcheck_endpoint }}"
    method: GET
    validate_certs: no
    status_code: 200
  register: portal_healthstatus_result
  until: portal_healthstatus_result.status == 200
  retries: 60 # 720 * 5 seconds = 1hour (60*60/5)
  delay: 5 # Every 5 seconds

- debug:
    var: portal_healthstatus_result
    
- name: generate token
  uri:
    url: "{{ portal_generatetoken_endpoint }}"
    method: POST
    body: "password={{ portal_admin_user_pw }}&username={{ portal_admin_user }}&client=referer&ip=&referer={{ federation_endpoint }}&expiration=30&f=json"
    validate_certs: no
    body_format: form-urlencoded
    return_content: yes
    status_code: 200
  register: portaltokenresult
- debug:
    var: portaltokenresult
    
- debug:
    var: portaltokenresult.json.token