---
- name: check if reachable federate server
  ansible.windows.win_uri:
    url: "{{ server_healthcheck_endpoint }}"
    method: GET
    validate_certs: no
    status_code: 200
  register: server_healthstatus_result
  until: server_healthstatus_result.status_code == 200
  retries: 60 # 720 * 5 seconds = 1hour (60*60/5)
  delay: 5 # Every 5 seconds

- name: update server role to hosting server
  ansible.windows.win_uri:
    url: "{{ federation_endpoint }}/servers/{{ register_server.json.serverId }}/update"
    method: POST
    body: "serverRole=HOSTING_SERVER&serverFunction=&f=json&token={{ tokenresult.json.token }}"
    content_type: application/x-www-form-urlencoded
    validate_certs: no
    status_code: 200
    return_content: yes
    url_timeout: 180
    headers:
      referer: "{{ federation_endpoint }}"
  register: update_serverrole_result
  poll: 3
  async: 60
  when: register_server.json.serverId is defined

- debug:
    var: update_serverrole_result