---
- name: update internal webcertificate
  uri:
    url: "{{ editserversetting_endpoint }}"
    method: POST
    body: "machineName={{ server_internal_fqdn }}&adminURL=https://{{ server_internal_fqdn }}:6443/arcgis/admin&webServerCertificateAlias={{ web_certificate_alias }}&f=json&token={{ tokenresult.json.token }}"
    validate_certs: no
    body_format: form-urlencoded
    return_content: yes
    headers:
      Referer: "https://{{ server_internal_fqdn }}:6443"
  register: edit_cert

- name: check if server is available
  uri:
    url: "{{ healthcheck_endpoint }}"
    method: GET
    validate_certs: no
    status_code: 200
  register: _result
  until: _result.status == 200
  retries: 60 # 720 * 5 seconds = 1hour (60*60/5)
  delay: 10 # Every 5 seconds

  