name: Manual Action for deployment and provisioning ArcGIS Enterprise on aws codebuild
# on:
#   push:
#     paths:
#       - 'envs/dev/infra/*.tf'
#       - 'envs/dev/infra/*.tfvars'
##########################
### Run Manually       ###
##########################
on: 
  workflow_call:
    inputs:
      subdomain:
        required: true
        default: "seed1"
      deploypurpose:
        required: false
        default: "dev"
      switchtarget:
        type: choice
        description: switch target
        options: 
        - blue
        - green

env:
  # set with your preferred AWS region, e.g. us-west-1
  AWS_REGION: ap-southeast-2
  # set with GitHub Actions role name
  AWS_ROLE_ARN: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-action-to-ec2
  ROLLE_SESSION_NAME: GithubAction-Deploy
  CODEBUILD_PROJECT_NAME: ${{ secrets.AWS_CODEBUILD_PROJECT }}
  DEPLOY_SUBDOMAIN: ${{ github.event.inputs.subdomain }}
  DEPLOY_PURPOSE: ${{ github.event.inputs.deploypurpose }}
  SWITCH_TARGET: ${{ github.event.inputs.switchtarget }}

defaults:
  run:
    working-directory: ./envs/

jobs:
  deploy-blue:
    uses: ./.github/workflows/dev-arcgis-system-deploy-app-blue.yaml
    # if manual-run, please comment out the following
    # if: contains(toJSON(github.event.commits.*.message), '@deploy-aws')
    with:
      subdomain: ${{ env.DEPLOY_SUBDOMAIN }}
      deploypurpose: ${{ env.DEPLOY_PURPOSE }}
  deploy-green:
    uses: ./.github/workflows/dev-arcgis-system-deploy-app-green.yaml
    # if manual-run, please comment out the following
    # if: contains(toJSON(github.event.commits.*.message), '@deploy-aws')
    with:
      subdomain: ${{ env.DEPLOY_SUBDOMAIN }}
      deploypurpose: ${{ env.DEPLOY_PURPOSE }}
  deploy-front:
    needs: [deploy-blue, deploy-green]
    uses: ./.github/workflows/dev-arcgis-system-deploy-app-front.yaml
    with:
      subdomain: ${{ env.DEPLOY_SUBDOMAIN }}
      switchtarget: ${{ env.SWITCH_TARGET }}